-- AlterTable
ALTER TABLE `testAddress` MODIFY `TELE_ZENT` INTEGER NULL,
    MODIFY `AENDERUNGS` VARCHAR(500) NULL,
    MODIFY `KATALOGVER` INTEGER NULL;

-- AlterTable
ALTER TABLE `testProject` MODIFY `ADATUM` VARCHAR(500) NULL,
    MODIFY `VDATUM` VARCHAR(500) NULL,
    MODIFY `PBDATUM` VARCHAR(500) NULL,
    MODIFY `PDATUM` VARCHAR(500) NULL;
